# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
# - task: InvokeRESTAPI@1
#   displayName: Slack
#   inputs:
#     connectionType: 'connectedServiceName'
#     serviceConnection: 'Slack' xapp-1-A01B21MMFGD-2128623254544-8c5b190b39903c0900bd712cade853b26b147acbfb221dd121f61df0d3878f6c'
#     method: 'POST'
#     body: '"text": "Hello, world."'
#     urlSuffix: T0NQM0TPH/BG81UDCG4/hxFm8AFEiCgq1FvVzQ8n484f
#     waitForCompletion: 'false'

- task: SlackNotification@6
  inputs:
    SlackApiToken: '$(SlackApi)'
    MessageAuthor: 'Slack Azure DevOps'
    Channel: '#test-channel'
    NotificationType: 'ChatMessage'
    Message: 'Test'
    UseVariableForMessage: true
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
