# ASP.NET

# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

# - task: SlackNotification@6
#   inputs:
#     SlackApiToken: '$(SlackApi)'
#     MessageAuthor: 'Azure DevOps'
#     Channel: '#test'
#     NotificationType: 'ChatMessage'
#     Title: 'Build started'
#     PreText: 'Release: $(CurrentRelease)'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      function Send-SlackMessage {
          param (
              [Parameter(Mandatory=$true, Position=0)]$Text,
              [Parameter(Mandatory=$true, Position=1)]$Url
          )
          $body= @"
          {
              "username": "Loading Bay",
              "text": "MESSAGE_TEXT",
              "icon_emoji":":rolled_up_newspaper:"
          }
      "@
      
          Invoke-WebRequest -Method Post -Uri $Url -Body $body.Replace("MESSAGE_TEXT","$Text") -ContentType 'application/json'
      }
      Write-Host "Sending slack message for BUILD: $($env:BUILD_BUILDID)"
      
      Send-SlackMessage "<#test> <https://dev.azure.com/SiarheiHudaryan/Siarhei_Hudaryan/_apps/hub/ms.vss-build-web.ci-designer-hub?pipelineId=7/results?buildId=$($env:BUILD_BUILDID)|Build: $($env:BUILD_BUILDID)> is now on STAGING" "https://hooks.slack.com/services/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"

- task: SlackNotification@6
  inputs:
    SlackApiToken: '$(SlackApi)'
    MessageAuthor: 'Azure DevOps test'
    Channel: '#test'
    NotificationType: 'ChatMessage'
    Message: 'Hello from *Slack notification*'
    Title: 'Build started in Pipline: $(Build.DefinitionName)'
    Text: "Build_repository: * $(Build.Repository.Name)*    Build number: * $(Build.BuildNumber)*"

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
